name: review-tools
version: '0.48+git'
summary: Review tools for snappy
description: |
  This snap provides the snap-review command as well as well as other tools
  related to snap review processes. These tools are used by the Ubuntu store
  and can be used to verify your snap before upload.
confinement: strict
base: core18

environment:
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  MAGIC: $SNAP/usr/share/misc/magic

apps:
  snap-review:
    command: snap-review
    plugs: [ home, mount-observe ]
    environment:
      FAKEROOTDONTTRYCHOWN: "1"
  snap-declaration:
    command: create-snap-declaration
    plugs: [ mount-observe ]
  updates-available:
    command: snap-updates-available
    plugs: [ home, mount-observe, network ]
  check-notices:
    command: snap-check-notices
    plugs: [ home, mount-observe, network ]
  fetch-usn-db:
    command: bin/fetch-db
    plugs: [ network ]
    environment:
      SYSTEM_WGETRC: $SNAP/etc/wgetrc
  swift:
    command: usr/bin/python3-swift
    plugs: [ mount-observe, network ]
  diffsquash:
    command: bin/diffsquash
    plugs: [ home ]

parts:
  review-tools:
    source: .
    plugin: python
    override-build: |
      snapcraftctl build
      cd $SNAPCRAFT_PART_BUILD
      ./override-build.sh
    build-packages:
    - binutils
    - dpkg
    - execstack
    - fakeroot
    - file
    - libmagic1
    - flake8
    - pylint3
    - python3-coverage
    - python3-magic
    - python3-simplejson
    - python3-yaml
    - squashfs-tools
    stage-packages:
    - binutils
    - dpkg
    - fakeroot
    - file
    - libdb5.3
    - libmagic1
    - python3-coverage
    - python3-magic
    - python3-simplejson
    - python3-yaml
    - squashfs-tools
    - python3-swiftclient
    - build-essential
    stage:
    - -usr/bin/2to3-3.5
    - -usr/bin/py3clean
    - -usr/bin/py3compile
    - -usr/bin/pydoc3.5
    - -usr/share/dh-python
    - -usr/share/python3/py3versions.py
    - -var/lib/ieee-data/mam.txt
    - -var/lib/ieee-data/oui36.txt
    - -usr/lib/python3/dist-packages/netaddr/eui/iab.txt
    - -usr/lib/python3/dist-packages/netaddr/eui/oui.txt

  # https://launchpad.net/bugs/1850861
  execstack:
    plugin: autotools
    source: .
    override-pull: |
      # pull the source from xenial if we haven't already
      if ! test -f ./debian/changelog ; then
        echo "deb-src http://archive.ubuntu.com/ubuntu/ xenial universe" > /etc/apt/sources.list.d/prelink.list
        echo "deb-src http://archive.ubuntu.com/ubuntu/ xenial-security universe" >> /etc/apt/sources.list.d/prelink.list
        apt-get update
        echo "apt-get source prelink and put in $(pwd)"
        tmpdir=$(mktemp -d prelink.XXXXXX --tmpdir=./)
        cd "$tmpdir"
        apt-get source prelink
        mv ./prelink-*/* ../
        cd ..
        rm -rf "$tmpdir"
      fi
    build-packages:
    - build-essential
    - libelf-dev
    - libpopt-dev
    - libselinux1-dev
    stage-packages:
    - libelf1
    stage:
    - -man
    - -sbin/prelink
    - -usr/share/doc
